#!/usr/bin/env bash

FILENAME="wintermute.ly"

show_help() {
  echo "Autobuild and autoplay script for LilyPond files."
  echo ""
  echo "USAGE:"
  printf "%-15s Only build the notes, don't play anything.\n" "$0"
  echo ""
  echo "FLAGS:"
  echo "-p, --pmidi     Play the generated MIDI file using pmidi."
  echo "                Recommended if you want to pass MIDI to an external synth."
  echo "-t, --timidity  Play the generated MIDI file using timidity."
  echo "-h, --help      Show this message."
}

case $1 in
  -h|--help)
    show_help
    exit 0
    ;;
  -t|--timidity)
    on_changed="lilypond $FILENAME || exit 1; killall timidity; timidity wintermute.midi &!"
    ;;
  -p|--pmidi)
    on_changed="lilypond $FILENAME || exit 1; killall pmidi; pmidi -p 128:0 wintermute.midi &!"
    ;;
  "") 
    on_changed="lilypond $FILENAME"
    ;;
  *)
    echo "Unrecognised command option: $1"
    echo
    show_help
    exit 1

  esac

  find $FILENAME | entr bash -c "$on_changed"
