name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  sheets:
    # Name the Job
    name: Sheets 
    # Set the type of machine to run on
    runs-on: ubuntu-20.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install LilyPond compiler
        run: sudo apt install lilypond -y
      
      - name: Build the sheets
        run: lilypond wintermute.ly

      - name: Archive the built sheets PDF
        uses: actions/upload-artifact@v2
        with:
          name: wintermute-sheets-pdf
          path: wintermute.pdf
